language: python
before_install: cd Server
python:
  - 3.6    
install:
  - pip install -r requirements.txt
script:
  - pytest
branches:
  only:
  - server
deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_API_KEY
  app: depressionserver
  on: server